openapi: 3.0.0

info:
  title: Fraud API Specification
  description: Fraud API Specification
  termsOfService: http://swagger.io/terms/
  contact:
    email: ricardorqr@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT

servers:
  - url: http://localhost:8082

tags:
  - name: Fraud
    description: Operations about fraudulend users
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io

paths:
  /fraud-check/{customerId}:

    get:
      tags:
        - Fraud
      summary: Check if a customer is fraudulent
      operationId: isFraudster
      parameters:
        - name: customerId
          in: path
          description: ID of the customer
          required: true
          schema:
            type: integer
          example: "123456"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: boolean
#                $ref: '#/components/schemas/FraudCheckResponse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: System Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

#security:
#  - token: []

components:
  schemas:

    FraudCheckDTO:
      type: object
      required:
        - isFraudster
      properties:
        isFraudster:
          description: Check if the user is a fraudster
          type: boolean
          example: true
#
#    FraudCheckRequest:
#      description: A customer request
#      type: object
#      allOf:
#        - $ref: '#/components/schemas/FraudCheckDTO'
#
    FraudCheckResponseNoMessage:
      description: A customer response
      type: object
      allOf:
        - $ref: '#/components/schemas/FraudCheckDTO'

    FraudCheckResponse:
      description: Fraud-check response
      type: object
      required:
        - message
      properties:
        message:
          description: Details about the response
          type: string
          example: Example of message
      allOf:
        - $ref: '#/components/schemas/FraudCheckDTO'

    Error:
      type: object
      description: The Error object contains information about the error
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: 666
        message:
          type: string
          example: Any error message
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'

#  securitySchemes:
#    token:
#      description: Plese, provide the security token
#      type: apiKey
#      name: token
#      in: header

